from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    FacilityAvailabilityView,
    FacilityBedsView,
    HealthView,
    UserViewSet,
    SignUpView,
    ParoleeListView,
    BedAssignView,
    BedHoldRequestView,
    BedUnassignView,
    BedNotesUpdateView,
    CurrentUserView,
    CsrfCookieView,
    ChangePasswordView,
    SessionLoginView,
    SessionLogoutView,
    ProviderBedCreateView,
    ProviderClientLookupView,
    ProviderFacilitiesView,
    ProviderHoldDecisionView,
    ProviderHoldListView,
    ProviderPlacementEndDateView,
    ProviderBedsView,
    ProviderAssignClientView,
)

router = DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    path("health/", HealthView.as_view()),
    path("auth/csrf/", CsrfCookieView.as_view()),
    path("auth/login/", SessionLoginView.as_view()),
    path("auth/logout/", SessionLogoutView.as_view()),
    path("auth/change-password/", ChangePasswordView.as_view()),
    path("me/", CurrentUserView.as_view()),
    path("facilities/availability/", FacilityAvailabilityView.as_view()),
    path("facilities/<int:facility_id>/beds/", FacilityBedsView.as_view()),
    path("parolees/", ParoleeListView.as_view()),
    path("beds/<int:bed_id>/assign/", BedAssignView.as_view()),
    path("beds/<int:bed_id>/hold/", BedHoldRequestView.as_view()),
    path("beds/<int:bed_id>/unassign/", BedUnassignView.as_view()),
    path("beds/<int:bed_id>/notes/", BedNotesUpdateView.as_view()),
    path("provider/facilities/", ProviderFacilitiesView.as_view()),
    path("provider/beds/create/", ProviderBedCreateView.as_view()),
    path("provider/beds/", ProviderBedsView.as_view()),
    path("provider/parolees/lookup/", ProviderClientLookupView.as_view()),
    path("provider/holds/", ProviderHoldListView.as_view()),
    path("provider/holds/<int:hold_id>/<str:decision>/", ProviderHoldDecisionView.as_view()),
    path("provider/placements/<int:parolee_id>/end-date/", ProviderPlacementEndDateView.as_view()),
    path("provider/assign-client/", ProviderAssignClientView.as_view()),
    path("signup/", SignUpView.as_view()),
    path("", include(router.urls)),
]