services:
  backend:
    ports:
      - "${HOST_PORT_API:-8000}:8000"
    volumes:
      - ./backend:/app
    env_file: .env
    environment:
      APP_ROOT: ${APP_ROOT:-}
    command:
      [
        "bash",
        "-lc",
        "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000",
      ]

  frontend:
    ports:
      - "${HOST_PORT:-5173}:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:8000
      VITE_API_PROXY_TARGET: http://backend:8000
      VITE_PUBLIC_URL: ${VITE_PUBLIC_URL:-}
      VITE_API_ROOT: ${VITE_API_ROOT:-}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command:
      [
        "bash",
        "-lc",
        "npm install && npm run dev -- --host 0.0.0.0 --port 5173",
      ]
