# Generated by Django 6.0.2 on 2026-04-21 01:15

import housing.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0007_merge_20260419_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='notes',
            field=housing.encryption.EncryptedField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=housing.encryption.EncryptedField(blank=True),
        ),
        migrations.AlterField(
            model_name='hold',
            name='reason',
            field=housing.encryption.EncryptedField(blank=True),
        ),
        migrations.AlterField(
            model_name='parolee',
            name='first_name',
            field=housing.encryption.EncryptedField(help_text='First name (encrypted)'),
        ),
        migrations.AlterField(
            model_name='parolee',
            name='idoc_id',
            field=housing.encryption.EncryptedCharField(help_text='IDOC-assigned identifier (encrypted)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='parolee',
            name='last_name',
            field=housing.encryption.EncryptedField(help_text='Last name (encrypted)'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_email',
            field=housing.encryption.EncryptedCharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_phone',
            field=housing.encryption.EncryptedCharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=housing.encryption.EncryptedCharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='notes',
            field=housing.encryption.EncryptedField(blank=True),
        ),
    ]
