# Generated by Django 6.0.2 on 2026-04-21 01:20

import housing.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0008_alter_bed_notes_alter_facility_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parolee',
            name='idoc_id',
            field=housing.encryption.EncryptedCharField(help_text='IDOC-assigned identifier (encrypted)', max_length=300, unique=True),
        ),
    ]
