# Generated by Django 6.0.2 on 2026-04-21 02:00

from django.db import migrations
import housing.encryption


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0009_alter_parolee_idoc_id'),
    ]

    operations = [
        # Keep idoc_id as EncryptedCharField for now - will convert to plain CharField in 0011
        # This migration does nothing - 0009 already set the correct size
        # The next migration (0011) will handle the decryption and type conversion
    ]
